=== vitorp4/BD-Academia-de-Musculacao/Projeto 2 - XML/transacao.dtd
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE TRANSACOES [
<!ELEMENT TRANSACOES (TRANSACAO)+>
<!ELEMENT TRANSACAO (CODIGO,ACAO,VALOR,DATA)>
<!ELEMENT CODIGO (#PCDATA)>
<!ELEMENT ACAO (#PCDATA)>
<!ELEMENT VALOR (#PCDATA)>
<!ELEMENT DATA (#PCDATA)>
]>

=== vitorp4/BD-Academia-de-Musculacao/Projeto 2 - XML/transacao.xml
<?xml version ="1.0" encoding="utf-8"?>
<!DOCTYPE transacao SYSTEM "transacao.dtd">
<?xml-stylesheet type="text/css" href="transacao.css"?>
<TRANSACOES>
	<TRANSACAO>
		<CODIGO>1</CODIGO>
		<ACAO>Venda</ACAO>
		<VALOR>50.00</VALOR>
		<DATA>02/02/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>2</CODIGO>
		<ACAO>Venda</ACAO>
		<VALOR>150.00</VALOR>
		<DATA>22/02/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>3</CODIGO>
		<ACAO>Compra</ACAO>
		<VALOR>250.00</VALOR>
		<DATA>24/02/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>4</CODIGO>
		<ACAO>Compra</ACAO>
		<VALOR>50.00</VALOR>
		<DATA>09/03/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>5</CODIGO>
		<ACAO>Venda</ACAO>
		<VALOR>450.00</VALOR>
		<DATA>09/03/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>6</CODIGO>
		<ACAO>Compra</ACAO>
		<VALOR>50.00</VALOR>
		<DATA>11/03/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>7</CODIGO>
		<ACAO>Venda</ACAO>
		<VALOR>580.00</VALOR>
		<DATA>15/04/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>8</CODIGO>
		<ACAO>Venda</ACAO>
		<VALOR>50.00</VALOR>
		<DATA>29/04/2017</DATA>
	</TRANSACAO>
	<TRANSACAO>
		<CODIGO>9</CODIGO>
		<ACAO>Compra</ACAO>
		<VALOR>550.00</VALOR>
		<DATA>03/05/2017</DATA>
	</TRANSACAO>
</TRANSACOES>
